export default[
    {
      "lmd_id": "119734",
      "store": "firstcry",
      "offer text": "20% Off on Baby Gear & Nursery Range",
      "title": "20% Off",
      "description": "Valid on Baby Gear & Nursery Range",
      "code": "FC20BGNR",
      "categories": "Kids and Toddlers,Baby Care,Baby Gears",
      "url": "http://www.firstcry.com/bikes,-ride-ons/7/90?scat=90%40~2852%40%40%40%40%40%40%40%40%401%400%4020%40%40%40%40%40%40%40%40%40%40",
      "type": "Code",
      "offer": "Offer",
      "offer value": "20%",
      "status": "Active",
      "start_date": "2016-05-24",
      "end_date": "2016-05-26"
    },
    {
      "lmd_id": "115961",
      "store": "firstcry",
      "offer text": "10% Off on All Diapers",
      "title": "10% Off",
      "description": "Valid on All Diapers",
      "code": "FC10DPR",
      "categories": "Kids and Toddlers,Baby Care",
      "url": "http://www.firstcry.com/baby-diapers/1/27?ref2=topoffer_diaper10cb_2Feb&c=FC10DPR",
      "type": "Code",
      "offer": "Cashback",
      "offer value": "10%",
      "status": "Active",
      "start_date": "2016-05-10",
      "end_date": "2016-12-22"
    },
    {
      "lmd_id": "118938",
      "store": "firstcry",
      "offer text": "20% Off on all products",
      "title": "20% Off",
      "description": "Valid on all products (For Kotak bank Bank users only)",
      "code": "FC20KOTAK",
      "categories": "Fashion,Kids and Toddlers,Kids Fashion,School Stuff,Baby Care,Maternity,Baby Gears",
      "url": "http://www.firstcry.com/",
      "type": "Code",
      "offer": "Offer",
      "offer value": "20%",
      "status": "Active",
      "start_date": "2016-05-20",
      "end_date": "2016-05-26"
    },
    {
      "lmd_id": "118937",
      "store": "firstcry",
      "offer text": "15% Off on all products",
      "title": "15% Off",
      "description": "Valid on all products (For Indus Ind Bank users only)",
      "code": "FCIND15",
      "categories": "Fashion,Mens Apparels,Womens Apparels,Watches,Ethnic Wear,Lingerie,Eyewear,Footwear,Handbags and Wallets,Jewellery,Fashion Accessories",
      "url": "http://www.firstcry.com/",
      "type": "Code",
      "offer": "Offer",
      "offer value": "15%",
      "status": "Active",
      "start_date": "2016-05-20",
      "end_date": "2016-05-26"
    },
    {
      "lmd_id": "118936",
      "store": "firstcry",
      "offer text": "20% Off on Baby Gear",
      "title": "20% Off",
      "description": "Valid on Baby Gear",
      "code": "MRBG20",
      "categories": "Kids and Toddlers,Baby Gears",
      "url": "http://www.firstcry.com/",
      "type": "Code",
      "offer": "Percentage-Off",
      "offer value": "20%",
      "status": "Active",
      "start_date": "2016-05-20",
      "end_date": "2016-05-26"
    },
    {
      "lmd_id": "118935",
      "store": "firstcry",
      "offer text": "15% Off For HDFC Bank Bank users only",
      "title": "15% Off",
      "description": "Valid For HDFC Bank Bank users only",
      "code": "FC15HDFC",
      "categories": "Kids and Toddlers,Kids Fashion,School Stuff,Baby Care,Maternity,Baby Gears",
      "url": "http://www.firstcry.com/",
      "type": "Code",
      "offer": "Offer",
      "offer value": "15%",
      "status": "Active",
      "start_date": "2016-05-20",
      "end_date": "2016-05-26"
    },
    {
      "lmd_id": "118934",
      "store": "firstcry",
      "offer text": "15% Off on all products",
      "title": "15% Off",
      "description": "Valid on all products (For AXIS Bank users only. Max. discount of Rs.500)",
      "code": "AXIS15FC",
      "categories": "Kids and Toddlers,Kids Fashion,School Stuff,Baby Care,Maternity,Baby Gears",
      "url": "http://www.firstcry.com/",
      "type": "Code",
      "offer": "Offer",
      "offer value": "15%",
      "status": "Active",
      "start_date": "2016-05-20",
      "end_date": "2016-05-26"
    },
    {
      "lmd_id": "118933",
      "store": "firstcry",
      "offer text": "Rs.300 Off on Selected Products",
      "title": "Rs.300 Off",
      "description": "Valid on Selected Products (On Min. Purchase of Rs.1299)",
      "code": "FY300",
      "categories": "Fashion,Kids and Toddlers,Kids Fashion,School Stuff,Baby Care,Maternity,Baby Gears",
      "url": "http://www.firstcry.com/",
      "type": "Code",
      "offer": "Price-Off",
      "offer value": "Rs.300",
      "status": "Active",
      "start_date": "2016-05-20",
      "end_date": "2016-05-26"
    },
    {
      "lmd_id": "118932",
      "store": "firstcry",
      "offer text": "25% Off on Baby And Nursery Gear Products",
      "title": "25% Off",
      "description": "Valid on Baby And Nursery Gear Products",
      "code": "MAY25BGNR",
      "categories": "Kids and Toddlers,Baby Care,Baby Gears",
      "url": "http://www.firstcry.com/",
      "type": "Code",
      "offer": "Percentage-Off",
      "offer value": "25%",
      "status": "Active",
      "start_date": "2016-05-20",
      "end_date": "2016-05-26"
    },
    {
      "lmd_id": "115970",
      "store": "firstcry",
      "offer text": "25% Off on Kids Clothes and Fashion Accessories",
      "title": "25% Off",
      "description": "Valid on Kids Clothes and Fashion Accessories (On Min. Purchase of Rs.750)",
      "code": "FC25CFF",
      "categories": "Fashion,Kids and Toddlers,Kids Fashion",
      "url": "http://www.firstcry.com/clothes-and-fashion-accessories?ref2=topoffer_fc_appl20",
      "type": "Code",
      "offer": "Percentage-Off",
      "offer value": "25%",
      "status": "Active",
      "start_date": "2016-05-10",
      "end_date": "2017-01-01"
    },
    {
      "lmd_id": "115969",
      "store": "firstcry",
      "offer text": "15% Off on Maternity Wear Lingerie",
      "title": "15% Off",
      "description": "Valid on Maternity Wear Lingerie (On Min. Purchase of Rs.750)",
      "code": "FC15MWL",
      "categories": "Fashion,Mens Apparels,Womens Apparels,Lingerie,Kids and Toddlers,Maternity",
      "url": "http://www.firstcry.com/searchresult.aspx?sale=21&brandid=0&searchstring=brand@~222~231~229~230~232~382~383@B@@1@0@21@@@@@@@@@@@@@@@@&sort=Popularity&ref2=topoffer_fc_Matwr15&c=FC15MWL",
      "type": "Code",
      "offer": "Percentage-Off",
      "offer value": "15%",
      "status": "Active",
      "start_date": "2016-05-10",
      "end_date": "2017-01-01"
    },
    {
      "lmd_id": "115968",
      "store": "firstcry",
      "offer text": "15% Off on Birthday & Gifts",
      "title": "15% Off",
      "description": "Valid on Birthday & Gifts (On Min. Purchase of Rs.751)",
      "code": "FC15BDAY",
      "categories": "Gift Items",
      "url": "http://www.firstcry.com/baby-kids-gifts?ref2=topoffer_fc_bdaygfts15&c=FC15BDAY",
      "type": "Code",
      "offer": "Percentage-Off",
      "offer value": "15%",
      "status": "Active",
      "start_date": "2016-05-10",
      "end_date": "2017-01-01"
    },
    {
      "lmd_id": "115967",
      "store": "firstcry",
      "offer text": "20% Off on Books, CD's & School Supplies",
      "title": "20% Off",
      "description": "Valid on Books, CD's & School Supplies",
      "code": "FC20BKSS",
      "categories": "Entertainment,CDs Books and Magazine,Kids and Toddlers,School Stuff",
      "url": "http://www.firstcry.com/back-to-school/10/0/0?ref2=topoffer_fc_bcdschool20&c=FC20BKSS",
      "type": "Code",
      "offer": "Percentage-Off",
      "offer value": "20%",
      "status": "Active",
      "start_date": "2016-05-10",
      "end_date": "2017-01-01"
    },
    {
      "lmd_id": "115966",
      "store": "firstcry",
      "offer text": "15% Off on Baby Gear & Nursery",
      "title": "15% Off",
      "description": "Valid on Baby Gear & Nursery",
      "code": "FC15BGNS",
      "categories": "Kids and Toddlers,Baby Care,Baby Gears",
      "url": "http://www.firstcry.com/baby-gear-and-nursery?ref2=topoffer_fc_bgn15&c=FC15BGNS",
      "type": "Code",
      "offer": "Percentage-Off",
      "offer value": "15%",
      "status": "Active",
      "start_date": "2016-05-10",
      "end_date": "2017-01-01"
    },
    {
      "lmd_id": "113460",
      "store": "firstcry",
      "offer text": "10% Off on Diapering Essentials",
      "title": "10% Off",
      "description": "Valid on Diapering Essentials (On Min. Purchase of Rs.750. Max. once per user, Not valid on Baby Diapers and the brands)",
      "code": "MAYAFDP10",
      "categories": "Fashion,Kids and Toddlers,Kids Fashion,Baby Care,Baby Gears",
      "url": "http://www.firstcry.com/diapering",
      "type": "Code",
      "offer": "Offer",
      "offer value": "10%",
      "status": "Active",
      "start_date": "2016-05-01",
      "end_date": "2016-06-01"
    },
    {
      "lmd_id": "115965",
      "store": "firstcry",
      "offer text": "15% discount on Toys and Gaming",
      "title": "15% discount",
      "description": "Valid on Toys and Gaming (on orders of Rs.750+)",
      "code": "FC15TOY",
      "categories": "Entertainment,Gaming,Board Games and Toys",
      "url": "http://www.firstcry.com/baby-kids-toys-store?ref2=topoffer_dc_fc_tyg15&c=FC15TOY",
      "type": "Code",
      "offer": "Percentage-Off",
      "offer value": "15%",
      "status": "Active",
      "start_date": "2016-05-10",
      "end_date": "2017-01-01"
    }]